#服务器端口
server:
  port: 8082
#mybatis mapper映射文件和扫描实体类配置文件     位置
mybatis:
  config-location: classpath:/mybatis/config/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
#mysql数据库驱动 url username  password
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root